version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
    php:
        build: ./docker/php
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html
        networks:
            - default
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./:/var/www/html
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: web
            MYSQL_PASSWORD: web
            MYSQL_DATABASE: web
        networks:
            - default
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - default

networks:
    default:
        driver: bridge