imports:
    - { resource: mailer.yml }

parameters:
    db.options:
        host: "%db.host%"
        port: "%db.port%"
        dbname: "%db.name%"
        user: "%db.user%"
        password: "%db.password%"

services:
    log.handler:
        class: Monolog\Handler\StreamHandler
        arguments: [ "%app.log_path%/%app.environment%.log" ]

    log:
        class: Monolog\Logger
        arguments: [ "main" ]
        calls:
            - [ pushHandler, [ "@log.handler" , "debug" ] ]

    db.driver:
        class: Doctrine\DBAL\Driver\PDOMySql\Driver

    db:
        class: Doctrine\DBAL\Connection
        arguments:
            - "%db.options%"
            - "@db.driver"

    redis:
        class: Redis
        calls:
            - [ connect, ['%redis.host%', '%redis.port%']]

    cache:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@redis'
            - ''
            - '%redis.ttl%'

    message_selector:
        class: Symfony\Component\Translation\MessageSelector

    yaml_loader:
        class: Symfony\Component\Translation\Loader\YamlFileLoader

    array_loader:
        class: Symfony\Component\Translation\Loader\ArrayLoader

    translator:
        class: Symfony\Component\Translation\Translator
        arguments: [ "en", "@message_selector" ]
        calls:
            - [ addLoader, [ "yaml", "@yaml_loader" ] ]
            - [ addLoader, [ "array", "@array_loader" ]]
            - [ addResource, [ "yaml", "%app.path%/l10n/de.yml", "de" ] ]
            - [ addResource, [ "yaml", "%app.path%/l10n/en.yml", "en" ] ]

    form.options:
        class: InputValidation\Form\Options\JsonOptions
        arguments:
            - "@translator"
        calls:
            - [ setOptionsPath, [ "%app.path%/options" ] ]

    form.validator:
        class: InputValidation\Form\Validator

    form.factory:
        class: InputValidation\Form\Factory
        arguments:
            - "@translator"
            - "@form.validator"
            - "@form.options"
        calls:
            - [ setFactoryNamespace, [ 'Weather\Form' ] ]
            - [ setFactoryPostfix, [ 'Form' ] ]

    form.user:
        class: Weather\Form\UserForm
        arguments: [ "@translator", "@form.validator", "@form.options" ]

    form.weatherquery:
        class: Weather\Form\WeatherQueryForm
        arguments: [ "@translator", "@form.validator", "@form.options" ]

    dao.factory:
        class: Doctrine\ActiveRecord\Dao\Factory
        arguments:
            - "@db"
        calls:
            - [ setFactoryNamespace, [ 'Weather\Dao' ] ]
            - [ setFactoryPostfix, [ 'Dao' ] ]

    model.factory:
        class: Doctrine\ActiveRecord\Model\Factory
        arguments:
            - "@dao.factory"
        calls:
            - [ setFactoryNamespace, [ 'Weather\Model' ] ]
            - [ setFactoryPostfix, [ '' ] ]

    model.user:
        class: Weather\Model\UserModel
        shared: false
        arguments: [ "@model.factory" ]

    service.mail:
        class: Weather\Service\Mail
        shared: false
        arguments: [ "@mailer", "@twig", { %app.email%: %app.name%} ]

    http.client:
        class: GuzzleHttp\Client

    rest.client:
        class: Weather\Client\RestClient
        arguments:
            - "@http.client"

    wunderground.client:
        class: Weather\Client\WundergroundClient
        arguments:
            - "@rest.client"
            - "%wunderground.apikey%"
            - "@cache"
        calls:
            - [ setLogger, ["@log"] ]
            - [ setCache, ['@cache']]